### ISSUE TITLE
Two timestamp on a single line yields only the first timestamp

### ISSUE THREAD

**Issue by MdFahimulIslam** [AlexFromXD/show-time#11]
For example:
"02/18/2021 21:01:16	[TMSG]	[Ntp]	ntp org: 3822670874 dst: 3822670876"

This line only shows date time of only the first timestamp.
### Right
![Snag_1e4deee2](https://user-images.githubusercontent.com/24982795/116115250-044b6d00-a6dc-11eb-936b-394e65ca6587.png)
### Wrong
![Snag_1e4deed2](https://user-images.githubusercontent.com/24982795/116115240-0281a980-a6dc-11eb-9952-fcb50c42c2b2.png)

**Comment by AlexFromXD** [comment]
thanks for reporting, i'll fix this ASAP

**Comment by AlexFromXD** [comment]
This problem has been solved, but due to some reason, I have republished the extension, so please remove the old one and reinstall, thanks.
